### ISSUE TITLE
Just Asking

### ISSUE THREAD

**Issue by ArnabBCA** [hppanpaliya/React-TrashMail#12]
Hi @hppanpaliya, I just found your project on GitHub, and it's awesome! Where are you hosting the SMTP server? Are there any limits? Also, where did you get the domain?

**Comment by hppanpaliya** [comment]
Hi @ArnabBCA,

Thank you for your kind words! I’m hosting the SMTP server on Oracle Cloud, taking advantage of their generous free tier for ARM CPU. For domains, I compare prices using [TLD List](https://tld-list.com/) to find the most cost-effective option.

I’m closing this issue now, but feel free to reopen it if needed.
